name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku container registry and CLI
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
          heroku container:login

      - name: Build Docker image
        run: docker build -t registry.heroku.com/precedent-parser/web .

      - name: Push Docker image to Heroku
        run: docker push registry.heroku.com/precedent-parser/web

      - name: Release Docker image on Heroku
        run: heroku container:release web -a precedent-parser

      - name: Set environment variables on Heroku
        run: |
          heroku config:set SCRAPEOPS_API_KEY=${{ secrets.SCRAPEOPS_API_KEY }} --app precedent-parser
          heroku config:set OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} --app precedent-parser
