name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku container registry and CLI
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API }}
        run: |
          echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
          heroku container:login
      - name: Debug Environment Variables
        run: |
          echo "SCRAPEOPS_API_KEY: ${{ secrets.SCRAPEOPS_API_KEY }}"
          echo "OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}"

      - name: Build and Deploy to Heroku
        env:
          SCRAPEOPS_API_KEY: ${{ secrets.SCRAPEOPS_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          docker build \
            --build-arg SCRAPEOPS_API_KEY=${SCRAPEOPS_API_KEY} \
            --build-arg OPENAI_API_KEY=${OPENAI_API_KEY} \
            -t registry.heroku.com/precedent-parser/web .
          
          docker push registry.heroku.com/precedent-parser/web
          heroku container:release web -a precedent-parser
